[book]
language = "en"
src = "src"
title = "The Adventures of Sherlock Holmes - Illustrated"

[output.html]
additional-css = [
    "src/font-family.css",
    "src/Gutenberg.css",
    "src/catppuccin.css"
]
