[book]
authors = ["Monty Williams"]
language = "en"
multilingual = false
src = "src"
title = "The Adventures of Sherlock Holmes (in Times New Roman font)"

[output.html]
additional-css = ["src/Gutenberg.css"]
theme = "src/theme"
